# Generated by Django 5.1.6 on 2025-02-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiml',
            old_name='childrens',
            new_name='children',
        ),
    ]
