version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER =postgres
      - POSTGRES_PASSWORD=admin

    depends_on:
      - pg

  pg:
    image: dpage/pgadmin4
    environment:
      - PGADMINDEFAULTEMAIL=admin@admin.command
      - PGADMINDEFAULTPASSWORD=admin
    ports:
      - "5432:5432"
