base:
  project: "aiml"
  random_state: 20
  target_col: "charges"

data_sources:
  raw_data_csv: data/raw/insurance.csv

load_data:
  clean_data: data/processed/insurance_1.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params: 
      alpha: 0.9
      l1_ratio: 0.6

model_path : models/models.joblib

reports:
  params: reports/params.json
  score: reports/scores.json